name: reward_app
description: A reward app with ads integration

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_mobile_ads: ^5.2.0
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  share_plus: ^7.0.0
  url_launcher: ^6.1.12
  animated_text_kit: ^4.2.2
  lottie: ^3.1.3
  confetti: ^0.8.0
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true